### PR TITLE
Added internationalization and translated examples to german

### LINKED ISSUE #116: State change problem with nextButtonText
The problem occurs when the props of the Stepzilla component change due to a state change of the parent component. In this case, the navigation buttons are re-rendered, with the exception of the Next button. Its text is determined by the state of the Stepzilla component.

### PR DESCRIPTION
**Pull request by tomtoxx**
Additionally I added a .gitattributes file to force git on Windows to check out files with lf eol and not with crlf eol.

This should help to fix #116

### CODE REVIEW

**Comment by newbreedofgeek** [comment]
@tomtoxx amazing work! that looks incredible.

CCing @aweber1 @agent3bood @zeel @Aapzu @elisechant @avivr  FYI - @tomtoxx found some issues that made StepZilla not work with i18n (Internationalization and localization), I've fixed the issue and he then made an cool example use case where the example can be translated in runtime.

image

But we might have a small issue - the previously simple example code we had that didn't include i18n is a bit more complex now. 

New users of StepZilla (there are close to 4000 per week now) who don't want i18n might find it harder to follow the example and integrate vanilla StepZilla into their project. This might lead to an influx of issues raised on github for help (which we don't want as we are already struggling to support the issues raised)

@tomtoxx can you think of some way to have both the existing vanilla example:
https://newbreedofgeek.github.io/react-stepzilla/

And the new example showing your amazing i18n update run side by side? for e.g. 
https://newbreedofgeek.github.io/react-stepzilla/i18n (not sure if this is possible as we are using gitthub pages for hosting)

If we cant do the above we should at least break out the `examples` directory into sub examples.

e.g. 
/examples --> the basic vanilla code
/examples/i18n --> the example with i18n

With the above we can support future use-cases of other example integrations as well without breaking the base basic vanilla example. (e.g. people have been asking for support for a redux sample)

What do you think? Lets discuss before we make the actual code update...

**Comment by tomtoxx** [comment]
I am glad that you like this example so much :smile:

Can understand your thoughts and agree with you. We should keep the example for beginners as simple as possible. 

A general splitting of the examples into subdirectories should not be a problem in my opinion and is probably the smartest way.

You might also be able to create a sample home page where the user can choose the desired example, e.g. the Vanilla example, the i18n example, and for completeness, I can create a new FontAwesome example to show the user that you can not only pass a string to `name:`, but also React components.

**Comment by newbreedofgeek** [comment]
Done via PR #122

**Comment by newbreedofgeek** [comment]
This was delivered via #122 - Instruction are here - https://github.com/newbreedofgeek/react-stepzilla/pull/122#issuecomment-433249716

**Pull request merged**
