### PR TITLE
Set nav states according to startAtStep

### PR DESCRIPTION
**Pull request by avivr**
Fixing a bug where navStates are not aligned when using 'startAtStep' prop.
The fix cause the steps to show correct 'done'/'in-progress'/'todo' styles.

### CODE REVIEW

**Comment by avivr** [comment]
Also added fix to set the buttons state according to the startAtStep

**Comment by darshan-raj** [comment]
Will this solve the issue where the "Previous" button is not visible when the startAtStep is greater than 0?

**Comment by avivr** [comment]
@darshan-raj yes, it solves this issue as well.

**Comment by newbreedofgeek** [comment]
@avivr thanks very much. It's been tested and merged. @darshan-raj yes this PR fixed it.

**Pull request merged**
