### PR TITLE
#81 for last step made class to done rather than doing

### LINKED ISSUE #81: Change last step to green checkbox on confirmation?
My last step, like your demo, thanks the user for their submission after they have walked through the steps.  The convention on the UI steps seems to be confusing our users (the gray circle at the end seems to indicate something else needs to be done - is it possible to force the last step to be a green checkbox?

It seems like the last "thank you step" should show all green checkboxes (I even just tried `return true` in the last step's `isValidated()` function but that didn't seem to help.

image

### PR DESCRIPTION
**Pull request by zeel**
fixed #81 

for last step changed classname to done to mark it complete.

### CODE REVIEW

**Comment by newbreedofgeek** [comment]
@zeel Actually the existing way the todo, doing and done classes are appended are correct. It shows a workflow. Changing the last step to 'done' when its actually 'doing' will break this css class workflow system.

Changing the last step to 'done' assumes that the last step is a 'success' step, what happens if its not a success step and instead the StepZilla was used like a slideshow to just show information?

I recommend the OP uses pure css to target the last.doing li and copy the style of the other checkboxes, like in the updated PR code

Please have a look at let me know what you think...

**Comment by gtwilliams03** [comment]
One comment (and maybe I am misunderstanding the convention) but I didn't want the `prevBtnOnLastStep` setting to be `true` on the last step since it is a final confirmation step that something was submitted successfully.  I prefer it to be `false` but still want the done state on the last step.

**Comment by newbreedofgeek** [comment]
@gtwilliams03 settings `prevBtnOnLastStep` setting to be true disables the "prev" button on the last step, this is useful for a workflow where the last step was a "thanks" message and you don't want the user to go back and change data. In this case, as I was suggesting we can make the final step CSS style to be `done` instead of `doing`.

If you want to keen the Prev button on the final step then its best you use pure CSS to get the style you want as[ recommended here ](https://github.com/newbreedofgeek/react-stepzilla/issues/81#issuecomment-379939076)

For this PR, I think we should make the simple fix as [mentioned above ](https://github.com/newbreedofgeek/react-stepzilla/pull/94#issuecomment-380635584) and merge this request in...

**Comment by zeel** [comment]
@newbreedofgeek I have fixed as [mentioned above](https://github.com/newbreedofgeek/react-stepzilla/pull/94/#issuecomment-379938831).

Let me know if any further changes are required.

**Comment by wonkywonka** [comment]
Any updates on this one, please ?

**Comment by newbreedofgeek** [comment]
@zeel thanks mate. This is merged in. @wonkywonka this is now available in v6.0.2

**Comment by wonkywonka** [comment]
Thank you mate, Made my day :) <3

**Pull request merged**
