### PR TITLE
added nextButtonCls backButtonCls #40

### PR DESCRIPTION
**Pull request by zeel**
#40 added nextButtonCls backButtonCls

### CODE REVIEW

**Comment by newbreedofgeek** [comment]
@zeel tnx for very for the complete work. I've (finally) merged this. Sorry for the delay.

**Comment by newbreedofgeek** [comment]
@zeel tnx for your work. I am struggling to find time to maintain StepZilla and (if you are keen) I've sent you an invite to collaborate on this repo. Basically I can use your help to triage the bugs and make fixes as needed. You did a great job in raising this PR (code quality was very good, tests were done etc) - so basically you just need to do the same for any other issues you want to fix. 

The steps to make code updates and test locally before pushing are here - https://github.com/newbreedofgeek/react-stepzilla/blob/master/CONTRIBUTING.md 

Let me know if you are keen? or reject the collaboration invite if you are not. Either way, tnx for your help.

**Comment by zeel** [comment]
@newbreedofgeek no problem. I will be happy to contribute to this repository. I will try to solve as many issues as I can thanks.

**Comment by zeel** [comment]
Hi @newbreedofgeek 

I created this PR long time back. Based on it can I get listed on contributors list for this app?

Thanks,
Zeel

**Pull request merged**
