### PR TITLE
 Changed PropType of step.name from string to object

### PR DESCRIPTION
**Pull request by tomtoxx**
Accordingly with the issue #113 

-  Changed PropType of step.name from string to object
- Updated samples and documentation

### CODE REVIEW

**Comment by newbreedofgeek** [comment]
@tomtoxx only issue with above is that if you its now an object, then if someone uses a string it will throw the proptype error?

**Comment by newbreedofgeek** [comment]
@tomtoxx also - sorry for the delay is looking at these PRs. I've been swamped with work on other projects.

**Comment by newbreedofgeek** [comment]
@tomtoxx  I've closed this off as the proposed fix would caused a error to be throw for others who were using string. I've fixed the issue in the commit dfc2b18 by allowing string and object. I have NOT tested with font awesome as you have so please make sure it work.

**Comment by tomtoxx** [comment]
Works great! :smile:

**Pull request closed without merging**
